server:
  port: 8085
  shutdown: immediate

spring:
  session:
    timeout: 1d
  main:
    web-application-type: servlet
  application:
    name: sba-server
  security:
    user:
      name: admin
      password: "{bcrypt}$2a$10$iIeJeLnH.eyWqPOCRkBiPefX3uSdmJW3t34JKU8bDZZNXRrN8RtH6"

  # Register this app as a Spring Boot Admin client of itself
  boot:
    admin:
      server:
        logging:
          file:
            enabled: true
      client:
        # URL of the Admin Server (this app itself)
        url: http://localhost:8085
        username: admin
        password: Temp01!
        auto-registration: true
        auto-deregistration: true
        instance:
          name: sba-server (self)
          prefer-ip: true
          management-base-url: http://localhost:8090
          # Credentials for the Admin Server to access actuator endpoints of this instance
          metadata:
            user.name: admin
            user.password: Temp01!
  devtools:
    restart:
      enabled: true
      poll-interval: 1000
      # Trigger full restart on any changes under src/main/resources/static
      # Override Boot's default exclude list (which normally ignores static/**)
      exclude: ""

info:
  app:
    name: ${spring.application.name}
    description: WebTemplate Spring Boot application
    version: ${project.version:0.0.1-SNAPSHOT}
    build-date: ${maven.build.timestamp:unknown}
    build-number: ${git.commit.id.abbrev:unknown}
#
#info:
#  app:
#    name: ${spring.application.name}
#    description: WebTemplate Spring Boot application
#    version: ${project.version:0.0.1-SNAPSHOT}
#    build-date: ${maven.build.timestamp:unknown}
#    build-number: ${git.commit.id.abbrev:unknown}

# Optional: set a context path for the Admin UI (e.g., "/admin"). Leave commented to use root.
# spring:
#   webflux: {}
# server:
#   servlet:
#     context-path: /admin

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
